"""Added local files

Revision ID: 3f39e2b65c07
Revises: a1b2c3d4e5f6
Create Date: 2025-12-19 00:34:03.778443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f39e2b65c07'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_parent_folder_id'), table_name='documents')
    op.drop_column('documents', 'parent_folder_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('parent_folder_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_documents_parent_folder_id'), 'documents', ['parent_folder_id'], unique=False)
    # ### end Alembic commands ###
