"""Add parent_folder_id to documents table

Revision ID: 6bbd67eacddd
Revises: 50b9e07440c8
Create Date: 2025-12-02 14:46:44.850565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bbd67eacddd'
down_revision: Union[str, Sequence[str], None] = '50b9e07440c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('parent_folder_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_documents_parent_folder_id'), 'documents', ['parent_folder_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_parent_folder_id'), table_name='documents')
    op.drop_column('documents', 'parent_folder_id')
    # ### end Alembic commands ###
